name: Publish to `mockzilla_web` pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - flutter_mockzilla_web-v**

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    runs-on: macos-14
    permissions:
      id-token: write
    environment: production
    steps:
      - name: Install dependencies
        run: bundle install
      - name: Download JS assets
        run: |
          export GPG_TTY=$(tty)
          bundle exec fastlane download_mockzilla_js_assets
      - uses: dart-lang/setup-dart@v1
      - run: cd mockzilla_web; flutter pub get
      - name: Publish
        run: cd mockzilla_web; dart pub publish --force
